#!/usr/bin/env python3
"""Generate grounded knowledge/*.txt fact files from the game's own data XML.

The chat brain (fpc_brain.py) grounds bot dialogue in tagged plain-text facts under
knowledge/. Hand-written files there are curated lore; this script emits the *accurate,
comprehensive* half straight from dist/game/data so bots reference real zones, real mobs
(with the levels this server actually uses), real gatekeeper destinations, real raid
bosses and real item names -- never invented ones. Re-run whenever the game data changes;
the facts can't drift from the live server because they're built from it.

    cd "L2J_Mobius_CT_0_Interlude github"
    python3 tools/build_knowledge.py
    # then restart fpc_brain.py so it reloads knowledge/

Output (each line is `[tag tokens] Fact text.`, the format retrieve() scores against):
    60_zones_generated.txt      one fact per hunting zone: level band + a few real mobs
    61_mobs_generated.txt       one fact per monster name: level + where it's found
    70_teleports_generated.txt  one fact per gatekeeper: town -> real destinations
    80_raidbosses_generated.txt one fact per raid boss: level + where
    90_items_generated.txt      real names for shots / scrolls / enchants / gemstones

Pure stdlib. Deterministic (sorted) so regeneration produces stable git diffs.
"""

import os
import re
import xml.etree.ElementTree as ET
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
PROJECT = os.path.dirname(HERE)  # the "L2J_Mobius_CT_0_Interlude github" dir
DATA = os.path.join(PROJECT, "dist", "game", "data")
OUT = os.path.join(PROJECT, "knowledge")

HEADER = ("# AUTO-GENERATED by tools/build_knowledge.py from dist/game/data -- DO NOT EDIT BY HAND.\n"
          "# Re-run the generator to refresh; hand edits are overwritten. Curated lore lives in the\n"
          "# non-'_generated' files. Format: [tag tokens] Fact text.\n")

# Spawn-folder -> the readable town/territory a bot would name.
TERRITORY_TOWN = {
    "TalkingIsland": "Talking Island", "Gludin": "Gludin Village", "Gludio": "Gludio",
    "Dion": "Dion", "Giran": "Giran", "Oren": "Oren", "Aden": "Aden",
    "Hunters": "Hunters Village", "Rune": "Rune", "Goddard": "Goddard",
    "Schuttgart": "Schuttgart", "Innadril": "Heine", "DarkElfTerritory": "the Dark Elf Village",
    "ElvenTerritory": "the Elven Village", "OrcTerritory": "the Orc Village",
    "DwarvenTerritory": "the Dwarven Village",
}

# Stop-tokens kept out of generated tag lists (they match nothing useful and add noise).
TAG_STOP = {"the", "of", "a", "an", "and", "near", "in", "at", "to"}

_CAMEL = re.compile(r"(?<=[a-z0-9])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])")


_LOWER_WORDS = {"of", "the", "and", "near", "for"}


def readable(stem):
    """Turn a spawn filename stem into a human zone name, or '' if it has no real name.

    'DragonValleyMonsters' -> 'Dragon Valley'; '19_16_PaganAltar' -> 'Pagan Altar'.
    Pure map-grid tiles like '17_20' (Others/ world-region files) have no name -> ''.
    """
    for suf in ("Monsters", "Monster", "Spawns", "Spawn", "NPCs", "NPC"):
        if stem.endswith(suf) and stem != suf:
            stem = stem[: -len(suf)]
    stem = stem.replace("_", " ")
    words = [w for w in _CAMEL.sub(" ", stem).split() if w]
    while words and words[0].isdigit():  # drop leading map-grid coordinates
        words.pop(0)
    if not words or all(w.isdigit() for w in words):
        return ""
    return " ".join(w.lower() if i and w.lower() in _LOWER_WORDS else w
                    for i, w in enumerate(words)).strip()


def tokens(text):
    toks = [t for t in re.findall(r"[a-z0-9]+", (text or "").lower()) if t not in TAG_STOP]
    seen, out = set(), []
    for t in toks:  # dedup, preserve order
        if t not in seen:
            seen.add(t)
            out.append(t)
    return out


def iter_xml(root_dir):
    for dp, _, fns in os.walk(root_dir):
        for fn in sorted(fns):
            if fn.endswith(".xml"):
                yield os.path.join(dp, fn)


def parse_root(path):
    try:
        return ET.parse(path).getroot()
    except ET.ParseError as e:
        print(f"  ! skip {os.path.relpath(path, DATA)}: {e}")
        return None


# ---- 1. NPCs: id -> (name, level, type) -------------------------------------
def load_npcs():
    npcs = {}
    for path in iter_xml(os.path.join(DATA, "stats", "npcs")):
        root = parse_root(path)
        if root is None:
            continue
        for npc in root.iter("npc"):
            nid = npc.get("id")
            name = npc.get("name")
            lvl = npc.get("level")
            typ = npc.get("type")
            if nid and name and lvl and lvl.isdigit():
                npcs[nid] = {"name": name, "level": int(lvl), "type": typ or ""}
    return npcs


# ---- 2. Spawns: zone files + npc -> zones + npc -> territory -----------------
def load_spawns():
    """Returns (zone_files, npc_zones, npc_territory).
    zone_files: list of (zone_name, territory_folder, {npc_id: count})
    npc_zones:  npc_id -> set(zone_name)
    npc_territory: npc_id -> territory_folder (first seen)."""
    zone_files = []
    npc_zones = defaultdict(set)
    npc_territory = {}
    spawn_root = os.path.join(DATA, "spawns")
    for path in iter_xml(spawn_root):
        root = parse_root(path)
        if root is None:
            continue
        rel = os.path.relpath(path, spawn_root)
        territory = rel.split(os.sep)[0]
        stem = os.path.splitext(os.path.basename(path))[0]
        zone = readable(stem)
        counts = defaultdict(int)
        for npc in root.iter("npc"):
            nid = npc.get("id")
            if not nid:
                continue
            try:
                counts[nid] += int(npc.get("count") or 1)
            except ValueError:
                counts[nid] += 1
            npc_territory.setdefault(nid, territory)
            if zone:  # skip nameless map-grid tiles as a "location"
                npc_zones[nid].add(zone)
        if counts and zone:
            zone_files.append((zone, territory, dict(counts), stem))
    return zone_files, npc_zones, npc_territory


# ---- Emit: zones -------------------------------------------------------------
def emit_zones(npcs, zone_files):
    lines = []
    for zone, territory, counts, stem in zone_files:
        if stem.endswith("NPCs"):  # town folk/merchant files, not a hunting ground
            continue
        mobs = [(nid, c) for nid, c in counts.items()
                if npcs.get(nid, {}).get("type") == "Monster"]
        if not mobs:
            continue
        levels = [npcs[nid]["level"] for nid, _ in mobs]
        lo, hi = min(levels), max(levels)
        # representative mobs: most numerous first, distinct names
        by_name = {}
        for nid, c in sorted(mobs, key=lambda x: (-x[1], npcs[x[0]]["level"])):
            nm = npcs[nid]["name"]
            by_name[nm] = by_name.get(nm, 0) + c
        reps = list(dict.fromkeys(by_name.keys()))[:3]
        town = TERRITORY_TOWN.get(territory)
        where = f"{zone} near {town}" if town else zone
        if len(reps) >= 2:
            mob_txt = f" Mobs there include {', '.join(reps[:-1])} and {reps[-1]}."
        elif reps:
            mob_txt = f" Mobs there include {reps[0]}."
        else:
            mob_txt = ""
        tag = tokens(zone) + (tokens(town) if town else [])
        tagstr = " ".join(["location", "level", str(lo), str(hi)] + tag)
        lines.append((zone.lower(),
                      f"[{tagstr}] {where} is a hunting zone around levels {lo}-{hi}.{mob_txt}"))
    lines.sort()
    return [l for _, l in lines]


# ---- Emit: per-monster index (answers "where is X mob?") --------------------
def emit_mobs(npcs, npc_zones):
    # group by monster name (many ids share a name); merge level range + zones
    by_name = {}
    for nid, info in npcs.items():
        if info["type"] != "Monster":
            continue
        nm = info["name"]
        rec = by_name.setdefault(nm, {"lo": info["level"], "hi": info["level"], "zones": set()})
        rec["lo"] = min(rec["lo"], info["level"])
        rec["hi"] = max(rec["hi"], info["level"])
        rec["zones"] |= npc_zones.get(nid, set())
    lines = []
    for nm in sorted(by_name):
        rec = by_name[nm]
        lvl = f"level {rec['lo']}" if rec["lo"] == rec["hi"] else f"levels {rec['lo']}-{rec['hi']}"
        zones = sorted(z for z in rec["zones"] if z)
        if zones:
            where = zones[0] if len(zones) == 1 else f"{zones[0]} and {zones[1]}"
            fact = f"{nm} ({lvl}) is found in {where}."
        else:
            fact = f"{nm} is a {lvl} monster."
        tag = " ".join(["mob"] + tokens(nm))
        lines.append(f"[{tag}] {fact}")
    return lines


# ---- Emit: raid bosses -------------------------------------------------------
def emit_raids(npcs, npc_zones):
    by_name = {}
    for nid, info in npcs.items():
        if info["type"] != "RaidBoss":
            continue
        rec = by_name.setdefault(info["name"], {"lvl": info["level"], "zones": set()})
        rec["zones"] |= npc_zones.get(nid, set())
    lines = []
    for nm in sorted(by_name):
        rec = by_name[nm]
        zones = sorted(z for z in rec["zones"] if z)
        where = f" It roams {zones[0]}." if zones else ""
        tag = " ".join(["raid", "boss", "raidboss"] + tokens(nm))
        lines.append(f"[{tag}] {nm} is a level {rec['lvl']} raid boss.{where}")
    return lines


# ---- Emit: gatekeeper destinations ------------------------------------------
def emit_teleports(npcs, npc_territory):
    tp_dir = os.path.join(DATA, "teleporters", "town")
    lines = []
    for path in iter_xml(tp_dir):
        root = parse_root(path)
        if root is None:
            continue
        gk_id = os.path.splitext(os.path.basename(path))[0]
        dests = []
        for tp in root.iter("teleport"):
            if tp.get("type") != "NORMAL":
                continue
            for loc in tp.findall("location"):
                nm = loc.get("name")
                if nm and nm not in dests:
                    dests.append(nm)
        if not dests:
            continue
        territory = npc_territory.get(gk_id)
        town = TERRITORY_TOWN.get(territory) if territory else None
        gk_name = npcs.get(gk_id, {}).get("name", "")
        who = f"The gatekeeper in {town}" if town else "A town gatekeeper"
        if gk_name:
            who += f" ({gk_name})"
        tag = ["gatekeeper", "gk", "teleport", "teleporter", "portal"]
        if town:
            tag += tokens(town)
        for d in dests:  # so "how do I get to <place>" matches the GK that reaches it
            tag += tokens(d)
        tag = list(dict.fromkeys(tag))
        lines.append((town or "zzz", gk_id,
                      f"[{' '.join(tag)}] {who} can teleport to: {', '.join(dests)}."))
    lines.sort()
    return [l for *_, l in lines]


# ---- Emit: item vocabulary (shots / scrolls / enchants / gemstones) ---------
ITEM_FAMILIES = [
    ("soulshot ss soulshots", re.compile(r"^Soulshot:", re.I)),
    ("blessed soulshot bss", re.compile(r"^Blessed Soulshot", re.I)),
    ("spiritshot sps spiritshots", re.compile(r"^Spiritshot:", re.I)),
    ("blessed spiritshot bsps bss", re.compile(r"^Blessed Spiritshot", re.I)),
    ("enchant weapon scroll ew", re.compile(r"^Scroll: Enchant Weapon", re.I)),
    ("enchant armor scroll ea", re.compile(r"^Scroll: Enchant Armor", re.I)),
    ("gemstone gem crafting", re.compile(r"^Gemstone", re.I)),
]
ITEM_SINGLE = [
    ("soe scroll escape teleport town", re.compile(r"^Scroll of Escape$", re.I)),
    ("resurrection res scroll", re.compile(r"^Scroll of Resurrection$", re.I)),
]


def emit_items():
    fam = {tag: [] for tag, _ in ITEM_FAMILIES}
    singles = {}
    for path in iter_xml(os.path.join(DATA, "stats", "items")):
        root = parse_root(path)
        if root is None:
            continue
        for item in root.iter("item"):
            nm = item.get("name")
            if not nm:
                continue
            for tag, rx in ITEM_FAMILIES:
                if rx.match(nm):
                    fam[tag].append(nm)
            for tag, rx in ITEM_SINGLE:
                if rx.match(nm):
                    singles[tag] = nm
    lines = []
    for tag, _ in ITEM_FAMILIES:
        names = sorted(set(fam[tag]))
        if not names:
            continue
        shown = names if len(names) <= 8 else names[:8]
        lines.append(f"[item {tag}] Real item names for this family: {', '.join(shown)}.")
    for tag, nm in singles.items():
        lines.append(f"[item {tag}] '{nm}' is the exact item name.")
    return lines


def write(fn, lines, blurb):
    path = os.path.join(OUT, fn)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(HEADER)
        fh.write(f"# {blurb}\n\n")
        fh.write("\n".join(lines) + "\n")
    print(f"  wrote {fn}: {len(lines)} facts")


def main():
    if not os.path.isdir(DATA):
        raise SystemExit(f"game data not found at {DATA}")
    os.makedirs(OUT, exist_ok=True)
    print("Loading NPC stats...")
    npcs = load_npcs()
    print(f"  {len(npcs)} npcs")
    print("Loading spawns...")
    zone_files, npc_zones, npc_territory = load_spawns()
    print(f"  {len(zone_files)} spawn files")
    print("Emitting knowledge files:")
    write("60_zones_generated.txt", emit_zones(npcs, zone_files),
          "Hunting zones with real level ranges and the mobs that spawn there.")
    write("61_mobs_generated.txt", emit_mobs(npcs, npc_zones),
          "Every monster: its level and where it is found (answers 'where is X mob?').")
    write("70_teleports_generated.txt", emit_teleports(npcs, npc_territory),
          "Gatekeeper teleport destinations per town.")
    write("80_raidbosses_generated.txt", emit_raids(npcs, npc_zones),
          "Raid bosses: level and location.")
    write("90_items_generated.txt", emit_items(),
          "Exact real item names for shot / scroll / enchant / gemstone families.")
    print("Done. Restart fpc_brain.py to reload the knowledge base.")


if __name__ == "__main__":
    main()
